<a href="https://colab.research.google.com/github/phamanhnhatminh1809/ThucHanhDeepLearning/blob/main/THDL_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy lý thuyết

Khai bao array 1 chieu

In [59]:
import numpy as np

# List -> Numpy array
list_input = [1,2,3,4]
arr_numpy = np.array(list_input)
print("Numpy array 1:", arr_numpy)

# Numpy array
arr_numpy = np.array([1,2,3,4])
print("Numpy array 1:", arr_numpy)

print(list_input * 2)
print(arr_numpy * 2)

Numpy array 1: [1 2 3 4]
Numpy array 1: [1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


Khai bao array 2 chieu

In [60]:
import numpy as np

arr_numpy = np.array([[1,2,3], [4, 5, 6]])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Type: int64


Khai bao array 3 chieu

In [63]:
import numpy as np

arr_numpy = np.array([[[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]]
                      ])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape: (4, 2, 3)
Type: int64


Tao array gia tri ban dau la 0 hoac 1

In [64]:
arr1 = np.zeros((2,2))
arr2 = np.ones((3,3))

print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[0. 0.]
 [0. 0.]]
arr2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape ma tran

In [68]:
arr_input = np.array([[1,2,3], [4,5,6]])
print("Truoc khi reshape")
print(arr_input)
print(arr_input.shape)
arr_input = arr_input.reshape(3, 2)
print("\nSau khi reshape")
print(arr_input)
print(arr_input.shape)

Truoc khi reshape
[[1 2 3]
 [4 5 6]]
(2, 3)

Sau khi reshape
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


Flatten ma tran

In [74]:
arr_input = np.array([[1,2,3], [4,5,6]])
print("\nFlatten mang 2 chieu")
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)
print("\nFlatten mang 3 chieu")
arr_input = np.array([[[1,2,3], [4,5,6]],
                      [[1,2,3], [4,5,6]]])
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)


Flatten mang 2 chieu
[1 2 3 4 5 6]
(6,)

Flatten mang 3 chieu
[1 2 3 4 5 6 1 2 3 4 5 6]
(12,)


1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [ ]:
import numpy as np

arr_input = np.random.randint(20, size = (3, 3))
result = np.all(arr_input != 0)
print("Ma tran la: \n", arr_input)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0:  Khong


2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [ ]:
import numpy as np

bt2 = np.random.randint(20, size = (3, 3))
result = np.any(bt1 != 0)
print("Ma tran la: \n", bt1)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0: Co


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
vector_1 = np.array([1,3])
vector_2 = np.array([2,2])

matrix_1 = np.array([[1,1], [3,3]])
matrix_2 = np.array([[2,2], [2,2]])

print(np.less(vector_1, vector_2))
print(np.less(matrix_1, matrix_2))

[ True False]
[[ True  True]
 [False False]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [ ]:
matrix_1x10 = np.full(10, 1)
matrix_0x10 = np.full(10, 0)
matrix_5x10 = np.full(10, 5)
print(matrix_1x10)
print(matrix_0x10)
print(matrix_5x10)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [ ]:
arr_30to70 = np.arange(30, 70)
print(arr_30to70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
(Tìm hiểu hàm identity của numpy)

In [ ]:
matrix_donvi = np.identity(3)

print(matrix_donvi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
đầu và cuối

In [ ]:
result = np.random.randint(15, 55, size = (3))[1:-1]
print(result)

[45]


8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
khoảng [9, 15]

In [8]:
import numpy as np

arr_input = np.random.randint(0, 20, size=10)
arr_condition = np.arange(9, 15)

condition = np.isin(arr_input, arr_condition)
result = np.where(condition, arr_input, -arr_input)

print(result)

[ 0  9  9  0  0  0  0 14  0 12]


9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [20]:
import numpy as np

result = np.random.randint(10, 21,size = (3,4))
print(result)

[[14 10 10 16]
 [13 10 14 14]
 [13 11 15 16]]


10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
giá trị 0

In [34]:
import numpy as np
matrix_10x10 = np.full((10, 10), 1)
matrix_10x10[1:-1, 1:-1] = 0
print(matrix_10x10)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
hàm diag của numpy)

In [38]:
import numpy as np
arr_5x5 = np.diag([1,2,3,4,5])
print(arr_5x5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
của numpy)

In [44]:
import numpy as np
arr_input = np.random.randint(10, size=(3,3,3))

sum_col = arr_input.sum(axis=0)
sum_row = arr_input.sum(axis=1)

print("Tổng cột:\n", sum_col)
print("Tổng hàng:\n", sum_row)

Tổng cột:
 [[11 10 11]
 [16 18 12]
 [18 14  6]]
Tổng hàng:
 [[11 16  4]
 [19 11 10]
 [15 15 15]]


13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [51]:
import numpy as np

v1 = np.random.randint(0, 10, size = 2)
v2 = np.random.randint(0, 10, size = 2)

inner_product = np.dot(v1, v2)
print("vector1:", v1)
print("vector2:", v2)
print("Inner product:", inner_product)

vector1: [7 8]
vector2: [2 7]
Inner product: 70


14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
ma trận A

In [54]:
import numpy as np

matrix_4x3 = np.full((4, 3), 0)
print(matrix_4x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
