<a href="https://colab.research.google.com/github/phamanhnhatminh1809/ThucHanhDeepLearning/blob/main/THDL_Tuan01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy lý thuyết**

Khai bao array 1 chieu

In [ ]:
# @title


In [59]:
# @title
import numpy as np

# List -> Numpy array
list_input = [1,2,3,4]
arr_numpy = np.array(list_input)
print("Numpy array 1:", arr_numpy)

# Numpy array
arr_numpy = np.array([1,2,3,4])
print("Numpy array 1:", arr_numpy)

print(list_input * 2)
print(arr_numpy * 2)

Numpy array 1: [1 2 3 4]
Numpy array 1: [1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


Khai bao array 2 chieu

In [60]:
# @title
import numpy as np

arr_numpy = np.array([[1,2,3], [4, 5, 6]])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Type: int64


Khai bao array 3 chieu

In [63]:
# @title
import numpy as np

arr_numpy = np.array([[[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]]
                      ])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape: (4, 2, 3)
Type: int64


Tao array gia tri ban dau la 0 hoac 1

In [64]:
# @title
arr1 = np.zeros((2,2))
arr2 = np.ones((3,3))

print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[0. 0.]
 [0. 0.]]
arr2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape ma tran

In [68]:
# @title
arr_input = np.array([[1,2,3], [4,5,6]])
print("Truoc khi reshape")
print(arr_input)
print(arr_input.shape)
arr_input = arr_input.reshape(3, 2)
print("\nSau khi reshape")
print(arr_input)
print(arr_input.shape)

Truoc khi reshape
[[1 2 3]
 [4 5 6]]
(2, 3)

Sau khi reshape
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


Flatten ma tran

In [74]:
# @title
arr_input = np.array([[1,2,3], [4,5,6]])
print("\nFlatten mang 2 chieu")
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)
print("\nFlatten mang 3 chieu")
arr_input = np.array([[[1,2,3], [4,5,6]],
                      [[1,2,3], [4,5,6]]])
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)


Flatten mang 2 chieu
[1 2 3 4 5 6]
(6,)

Flatten mang 3 chieu
[1 2 3 4 5 6 1 2 3 4 5 6]
(12,)


Hstack va Vstack

In [75]:
# @title
arr_input1 = np.array([1, 2, 3])
arr_input2 = np.array([4, 5, 6])

h_stack = np.hstack((arr_input1, arr_input2))
v_stack = np.vstack((arr_input1, arr_input2))

print("Horizon append:\n", h_stack)
print("Vertical append:\n", v_stack)

Horizon append:
 [1 2 3 4 5 6]
Vertical append:
 [[1 2 3]
 [4 5 6]]


Sinh mang so ngau nhien

In [86]:
# @title
import numpy as np

arr_input1 = np.random.randint(0, 100, size = (5))
arr_input2 = np.random.randint(0, 100, size = (3, 2))
arr_input3 = np.random.randint(0, 100, size = (2,3,4))
print("arr_input 1:\n", arr_input1)
print("\narr_input 2:\n", arr_input2)
print("\narr_input 3:\n", arr_input3)

arr_input 1:
 [97 84 67 51 54]

arr_input 2:
 [[67 75]
 [42 17]
 [41 27]]

arr_input 3:
 [[[48 94 22  5]
  [72 50 36  1]
  [63 28 66 99]]

 [[70 91 75 87]
  [56 47 36 40]
  [68 36 20 72]]]


1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [ ]:
# @title
import numpy as np

arr_input = np.random.randint(20, size = (3, 3))
result = np.all(arr_input != 0)
print("Ma tran la: \n", arr_input)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0:  Khong


Sinh mảng số thực trong khoảng

In [90]:
# @title
arr_rand_0_1_1D = np.random.rand(5)
arr_rand_0_1_2D = np.random.rand(3, 4)
arr_rand_0_1_3D = np.random.rand(3, 4, 2)

print("\nMang 1 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_1D)
print("\nMang 2 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_2D)
print("\nMang 3 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_3D)


Mang 1 chieu random trong khoang [0,1]: 
[0.75382807 0.47230622 0.99046255 0.77474397 0.71135964]

Mang 2 chieu random trong khoang [0,1]: 
[[0.24600128 0.95558442 0.40432254 0.6108692 ]
 [0.56883476 0.06317437 0.53470011 0.64229923]
 [0.31965581 0.08674388 0.11604232 0.56342766]]

Mang 3 chieu random trong khoang [0,1]: 
[[[0.31098949 0.47621446]
  [0.62006375 0.95399032]
  [0.36087872 0.51104797]
  [0.81415445 0.08513495]]

 [[0.35483128 0.88325815]
  [0.82244641 0.02262562]
  [0.89998236 0.41395096]
  [0.37055281 0.16830965]]

 [[0.95029107 0.47479231]
  [0.93859501 0.86354881]
  [0.73442156 0.45684583]
  [0.75315042 0.26440212]]]


Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [94]:
# @title
# np.random.normal (loc, scale, size)
# loc: Giá trị trung tâm
# scale: Độ lệch chuẩn
# size: Số phần tử trả về
arr_Gaussian = np.random.normal(5, 0.5, 10)
print(arr_Gaussian)

Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [104]:
# @title
arr_input = np.array([1,2,3,4,5,6,7,8,9,10])
choice_1 = np.random.choice(arr_input)
choice_3x5 = np.random.choice(arr_input, size=(3,5))
print("Sinh 1 gia tri ngau nhien tu mang cho truoc")
print(choice_1)
print("Sinh ma tran 3x5 gia tri ngau nhien tu mang cho truoc")
print(choice_3x5)

Sinh 1 gia tri ngau nhien tu mang cho truoc
4
Sinh ma tran 3x5 gia tri ngau nhien tu mang cho truoc
[[5 1 1 9 7]
 [8 1 6 2 4]
 [6 1 4 9 2]]


Thay đổi giá trị của ma trận

In [116]:
# @title
arr_input = np.matrix(np.ones((5,5)))
print("Ma tran:\n", arr_input)
np.asarray(arr_input)[2] = 2
print("Thay doi hang 3:\n", arr_input)

Ma tran:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Ma tran:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# **Numpy bài tập**

2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [ ]:
# @title
import numpy as np

bt2 = np.random.randint(20, size = (3, 3))
result = np.any(bt1 != 0)
print("Ma tran la: \n", bt1)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0: Co


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
# @title
vector_1 = np.array([1,3])
vector_2 = np.array([2,2])

matrix_1 = np.array([[1,1], [3,3]])
matrix_2 = np.array([[2,2], [2,2]])

print(np.less(vector_1, vector_2))
print(np.less(matrix_1, matrix_2))

[ True False]
[[ True  True]
 [False False]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [ ]:
# @title
matrix_1x10 = np.full(10, 1)
matrix_0x10 = np.full(10, 0)
matrix_5x10 = np.full(10, 5)
print(matrix_1x10)
print(matrix_0x10)
print(matrix_5x10)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [ ]:
# @title
arr_30to70 = np.arange(30, 70)
print(arr_30to70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
(Tìm hiểu hàm identity của numpy)

In [ ]:
# @title
matrix_donvi = np.identity(3)

print(matrix_donvi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
đầu và cuối

In [ ]:
# @title
result = np.random.randint(15, 55, size = (3))[1:-1]
print(result)

[45]


8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
khoảng [9, 15]

In [8]:
# @title
import numpy as np

arr_input = np.random.randint(0, 20, size=10)
arr_condition = np.arange(9, 15)

condition = np.isin(arr_input, arr_condition)
result = np.where(condition, arr_input, -arr_input)

print(result)

[ 0  9  9  0  0  0  0 14  0 12]


9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [20]:
# @title
import numpy as np

result = np.random.randint(10, 21,size = (3,4))
print(result)

[[14 10 10 16]
 [13 10 14 14]
 [13 11 15 16]]


10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
giá trị 0

In [34]:
# @title
import numpy as np
matrix_10x10 = np.full((10, 10), 1)
matrix_10x10[1:-1, 1:-1] = 0
print(matrix_10x10)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
hàm diag của numpy)

In [38]:
# @title
import numpy as np
arr_5x5 = np.diag([1,2,3,4,5])
print(arr_5x5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
của numpy)

In [44]:
# @title
import numpy as np
arr_input = np.random.randint(10, size=(3,3,3))

sum_col = arr_input.sum(axis=0)
sum_row = arr_input.sum(axis=1)

print("Tổng cột:\n", sum_col)
print("Tổng hàng:\n", sum_row)

Tổng cột:
 [[11 10 11]
 [16 18 12]
 [18 14  6]]
Tổng hàng:
 [[11 16  4]
 [19 11 10]
 [15 15 15]]


13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [51]:
# @title
import numpy as np

v1 = np.random.randint(0, 10, size = 2)
v2 = np.random.randint(0, 10, size = 2)

inner_product = np.dot(v1, v2)
print("vector1:", v1)
print("vector2:", v2)
print("Inner product:", inner_product)

vector1: [7 8]
vector2: [2 7]
Inner product: 70


14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
ma trận A

In [54]:
# @title
import numpy as np

matrix_4x3 = np.full((4, 3), 0)
print(matrix_4x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


# **Tensor lý thuyết**

Tensor 0 chiều

In [120]:
import tensorflow as tf

rank0_tensor = tf.constant(4)
r1_int = tf.constant(4, tf.int16)
r2_float = tf.constant(4.0, tf.float32)
r3_string = tf.constant("Hello HUIT", tf.string)

print(rank0_tensor)
print(r1_int)
print(r2_float)
print(r3_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int16)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(b'Hello HUIT', shape=(), dtype=string)


Tensor 1-chiều

In [121]:
import tensorflow as tf

rank1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


Tensor 2-chiều (ma trận)

In [122]:
import tensorflow as tf

rank2_tensor = tf.constant([[1,2], [3,4], [5,6]])
print(rank2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


Tensor n-chiều (nhiều trục)

In [126]:
rank_3_tensor = tf.constant([
    [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]]
])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]], shape=(3, 2, 3), dtype=int32)


Tạo tensor tự động gán giá trị 0 ban đầu

In [132]:
rank1_zero = tf.zeros(10)
print(rank1_zero)

rank2_zero = tf.zeros([2,3])
print(rank2_zero)

rank3_zero = tf.zeros([2, 3, 3])
print(rank3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


Tạo tensor tự động với giá trị bất kỳ

In [135]:
rank1 = tf.fill(3,10)
print(rank1)

rank2 = tf.fill([2,2],1)
print(rank2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


Tạo tensor 1-chiều với hàm linspace


In [136]:
# Hàm linspace tạo một tensor với số phần tử mong muốn trong một phạm vi nhất định
lin_tensor = tf.linspace(5, 2, 3)
print(lin_tensor)

tf.Tensor([5.  3.5 2. ], shape=(3,), dtype=float64)


Tạo tensor 1-chiều với hàm range

In [141]:
range_tensor = tf.range(3, 7, 0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


Tạo tensor với giá trị ngẫu nhiên

In [147]:
# normal
range_tensor = tf.random.normal([5])
print("\nNormal:")
print(range_tensor)
range_tensor = tf.random.normal([3,3])
print(range_tensor)

# truncated
range_tensor = tf.random.truncated_normal([5])
print("\nTruncated normal:")
print(range_tensor)
range_tensor = tf.random.truncated_normal([3,3])
print(range_tensor)

# uniform
range_tensor = tf.random.uniform([5])
print("\nUniform:")
print(range_tensor)
range_tensor = tf.random.uniform([3,3])
print(range_tensor)


Normal:
tf.Tensor([-0.2846495  -1.3848633  -0.80137026 -0.9842483   2.5473914 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 5.3582501e-02 -8.6850774e-01 -1.6533083e-01]
 [-1.1131105e+00  8.4209430e-04  3.2286305e-02]
 [-8.1277877e-01 -1.0661209e+00  1.2439115e+00]], shape=(3, 3), dtype=float32)

Truncated normal:
tf.Tensor([ 0.06816915  0.2126186   0.01331513 -0.07993142  0.189185  ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.09438159 -0.32365647  0.22455426]
 [-0.8297255   0.46307132 -1.7049134 ]
 [ 0.09177887 -1.094745    0.41500062]], shape=(3, 3), dtype=float32)

Uniform:
tf.Tensor([0.4493382  0.91022694 0.14004326 0.05444658 0.6803819 ], shape=(5,), dtype=float32)
tf.Tensor(
[[0.01586652 0.49280667 0.4354254 ]
 [0.1795038  0.32228732 0.40993798]
 [0.6389053  0.89317036 0.8799957 ]], shape=(3, 3), dtype=float32)


Chuyển đổi kiểu dữ liệu

In [152]:
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
t_int = tf.cast(t_float, dtype = tf.int32)
print(t_float, '---', t_float.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>


Cac phep toan trong tensor flow

In [154]:
# Can bac 2
x = tf.constant(2, dtype=tf.float32)

# Cong 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a,b)
tong = a + b

# Nhan 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a,b)
tich = a * b

print(x)
print(tong)
print(tich)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [ ]:
import tensorflow as tf

a = tf.constant([6. , 6. , 6.])
b = tf.constant([4. , 4. , 4.])
c = tf.constant([3. , 3. , 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

Các phép toán làm tròn và so sánh

In [155]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r1)
print(r2)
print(r3)
print(r4)

tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


Biến trong tensorflow

In [ ]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

Biến trong tensorflow

In [159]:
var1 = tf.Variable(8.5, dtype = tf.float32)
var2 = tf.Variable([5,9], dtype = tf.float32)
print(var1)
print(var1.shape)
print(var1.dtype)
print(var2)
print(var2.shape)
print(var2.dtype)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
()
<dtype: 'float32'>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 9.], dtype=float32)>
(2,)
<dtype: 'float32'>


Môi trường tính toán Graph trong tensorFlow

In [ ]:
def linear_regression(x, a, b):
    x = tf.matmul(x, a)
    x = x + b
    return x

graph_function = tf.function(linear_regression)

x1 = tf.constant([[1.0, 2.0]])
a1 = tf.constant([[2.0, 3.0]]
b1 = tf.constant(4)

original_value = graph_function(x1, y1, b1).numpy()
fu