# **3. Numpy lý thuyết**

3.1. Khai bao array 1 chieu

In [ ]:
# @title
import numpy as np

# List -> Numpy array
list_input = [1,2,3,4]
arr_numpy = np.array(list_input)
print("Numpy array 1:", arr_numpy)

# Numpy array
arr_numpy = np.array([1,2,3,4])
print("Numpy array 1:", arr_numpy)

print(list_input * 2)
print(arr_numpy * 2)

Numpy array 1: [1 2 3 4]
Numpy array 1: [1 2 3 4]
[1, 2, 3, 4, 1, 2, 3, 4]
[2 4 6 8]


3.2. Khai bao array 2 chieu

In [ ]:
# @title
import numpy as np

arr_numpy = np.array([[1,2,3], [4, 5, 6]])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Type: int64


3.3. Khai bao array 3 chieu

In [ ]:
# @title
import numpy as np

arr_numpy = np.array([[[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]],
                      [[1,2,3], [4, 5, 6]]
                      ])
print("Numpy array:\n", arr_numpy)
print("Shape:", arr_numpy.shape)
print("Type:", arr_numpy.dtype)

Numpy array:
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Shape: (4, 2, 3)
Type: int64


3.4. Tao array gia tri ban dau la 0 hoac 1

In [ ]:
# @title
arr1 = np.zeros((2,2))
arr2 = np.ones((3,3))

print("arr1:\n", arr1)
print("arr2:\n", arr2)

arr1:
 [[0. 0.]
 [0. 0.]]
arr2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


3.5. Reshape ma tran

3.5.1 Reshape thay đổi kích thước ma trận

In [ ]:
# @title
arr_input = np.array([[1,2,3], [4,5,6]])
print("Truoc khi reshape")
print(arr_input)
print(arr_input.shape)
arr_input = arr_input.reshape(3, 2)
print("\nSau khi reshape")
print(arr_input)
print(arr_input.shape)

Truoc khi reshape
[[1 2 3]
 [4 5 6]]
(2, 3)

Sau khi reshape
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


3.5.2.Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
# @title
arr_input = np.array([[1,2,3], [4,5,6]])
print("\nFlatten mang 2 chieu")
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)
print("\nFlatten mang 3 chieu")
arr_input = np.array([[[1,2,3], [4,5,6]],
                      [[1,2,3], [4,5,6]]])
arr_input = arr_input.flatten()
print(arr_input)
print(arr_input.shape)


Flatten mang 2 chieu
[1 2 3 4 5 6]
(6,)

Flatten mang 3 chieu
[1 2 3 4 5 6 1 2 3 4 5 6]
(12,)


3.6. Thêm dòng dữ liệu với hstack và vstack

In [ ]:
# @title
arr_input1 = np.array([1, 2, 3])
arr_input2 = np.array([4, 5, 6])

h_stack = np.hstack((arr_input1, arr_input2))
v_stack = np.vstack((arr_input1, arr_input2))

print("Horizon append:\n", h_stack)
print("Vertical append:\n", v_stack)

Horizon append:
 [1 2 3 4 5 6]
Vertical append:
 [[1 2 3]
 [4 5 6]]


3.7. Sinh mảng số nguyên ngẫu nhiên

3.7.1. Sinh mảng số nguyên ngẫu nhiên

In [ ]:
# @title
import numpy as np

arr_input1 = np.random.randint(0, 100, size = (5))
arr_input2 = np.random.randint(0, 100, size = (3, 2))
arr_input3 = np.random.randint(0, 100, size = (2,3,4))
print("arr_input 1:\n", arr_input1)
print("\narr_input 2:\n", arr_input2)
print("\narr_input 3:\n", arr_input3)

arr_input 1:
 [49 59 73 86 79]

arr_input 2:
 [[61 83]
 [ 8 89]
 [21 10]]

arr_input 3:
 [[[89 97 37 43]
  [ 9 35 45 41]
  [19 31 46  9]]

 [[65 86  5 94]
  [43 36 81  6]
  [69 20 63 40]]]


3.7.2. Sinh mảng số thực trong khoảng

In [ ]:
# @title
arr_rand_0_1_1D = np.random.rand(5)
arr_rand_0_1_2D = np.random.rand(3, 4)
arr_rand_0_1_3D = np.random.rand(3, 4, 2)

print("\nMang 1 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_1D)
print("\nMang 2 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_2D)
print("\nMang 3 chieu random trong khoang [0,1]: ")
print(arr_rand_0_1_3D)


Mang 1 chieu random trong khoang [0,1]: 
[0.58617535 0.67707373 0.12544972 0.09373872 0.81859651]

Mang 2 chieu random trong khoang [0,1]: 
[[0.46966868 0.752068   0.5844077  0.19039471]
 [0.10428813 0.26037745 0.48878174 0.51361737]
 [0.57978439 0.20170408 0.23077184 0.91119826]]

Mang 3 chieu random trong khoang [0,1]: 
[[[0.1701592  0.70598522]
  [0.85842789 0.15548814]
  [0.6590725  0.04057341]
  [0.63063144 0.93367509]]

 [[0.78487481 0.99826446]
  [0.43619636 0.13962225]
  [0.4786704  0.1217372 ]
  [0.85004737 0.46551026]]

 [[0.61743649 0.87785725]
  [0.84958144 0.63968052]
  [0.38563931 0.60737639]
  [0.41293367 0.36496002]]]


3.7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

In [ ]:
# @title
# np.random.normal (loc, scale, size)
# loc: Giá trị trung tâm
# scale: Độ lệch chuẩn
# size: Số phần tử trả về
arr_Gaussian = np.random.normal(5, 0.5, 10)
print(arr_Gaussian)

3.7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
# @title
arr_input = np.array([1,2,3,4,5,6,7,8,9,10])
choice_1 = np.random.choice(arr_input)
choice_3x5 = np.random.choice(arr_input, size=(3,5))
print("Sinh 1 gia tri ngau nhien tu mang cho truoc")
print(choice_1)
print("Sinh ma tran 3x5 gia tri ngau nhien tu mang cho truoc")
print(choice_3x5)

Sinh 1 gia tri ngau nhien tu mang cho truoc
4
Sinh ma tran 3x5 gia tri ngau nhien tu mang cho truoc
[[5 1 1 9 7]
 [8 1 6 2 4]
 [6 1 4 9 2]]


3.8. Thay đổi giá trị của ma trận

In [ ]:
# @title
matrix_5x5 = np.matrix(np.ones((5,5)))
print("Ma tran ban dau: \n", matrix_5x5)
np.array(matrix_5x5)[2] = 2
print("Doi gia tri dong thu 3 voi array: \n", matrix_5x5)
np.asarray(matrix_5x5)[2] = 2
print("Doi gia tri dong thu 3 voi asarray: \n", matrix_5x5)


Ma tran ban dau: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Doi gia tri dong thu 3 voi array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Doi gia tri dong thu 3 voi asarray: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


3.9. Sinh dãy số theo khoảng cho trước

In [ ]:
# @title
import numpy as np

#arange
arange_1 = np.arange(1, 20)
arange_2 = np.arange(1, 20, 2)
print("arange_1: ", arange_1)
print("arange_2: ", arange_2)

#linspace
# num: Số lượng phần tử có trong khoảng 1 - 5
linspace_1 = np.linspace(1. , 5., num=10)
print("linspace_1: ", linspace_1)

arange_1:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
arange_2:  [ 1  3  5  7  9 11 13 15 17 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


3.10. Index và slice

In [ ]:
# @title
#slice
slice_1 = np.array([(1, 2, 3),
                    (4, 5, 6)])
print("slice_1:\n", slice_1)
print("first row:", slice_1[0])
print("second row:", slice_1[1])

#indexing
print('second column: ', slice_1[:,1])
print('first column: ', slice_1[:,2])
print('First two values of second row: ', slice_1[1, :2])

slice_1:
 [[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
second column:  [2 5]
first column:  [3 6]
First two values of second row:  [4 5]


# **4. Pandas lý thuyết**

6. Đối tượng series

In [ ]:
# @title
import pandas as pd
#Tao pandas series tu list
pd_series1 = pd.Series([1., 2., 3.])
print(pd_series1)
print("Gia tri dau tien: ", pd_series1[0])
pd_series2 = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(pd_series2)
print("Gia tri dau tien: ", pd_series2['a'])

#Tao pandas series tu dictionary
calories = {"day1": 420, "day2":380, "day3":390}
to_series = pd.Series(calories)
print(to_series)

0    1.0
1    2.0
2    3.0
dtype: float64
Gia tri dau tien:  1.0
a    1.0
b    2.0
c    3.0
dtype: float64
Gia tri dau tien:  1.0
day1    420
day2    380
day3    390
dtype: int64


7. Tạo đối tượng Dataframe

In [ ]:
# @title
import pandas as pd

# Numpy --> Pandas
numpy_arr = np.array([[1,2], [3, 4]])
panda_arr = pd.DataFrame(numpy_arr)
print('DataFrame:\n', panda_arr)

# Pandas --> Numpy
numpy_arr = np.array(panda_arr)
print('Numpy array:\n', numpy_arr)

# Tạo Dataframe mảng 2 chiều có tên cột
dictionary_1 = {"Name":['Jonh', 'Smith'], 'Age':[30, 40]}
dataframe_dictionary_1 = pd.DataFrame(dictionary_1)
print('Dataframe dictionary: \n', dataframe_dictionary_1)

# Tạo mảng 20x4
random_matrix = np.random.randn(20, 4)
dataframe_1 = pd.DataFrame(random_matrix, columns = ['so1', 'so2', 'so3', 'so4'])
print('Dataframe dictionary: \n', dataframe_1.head())

# Chọn 1 cột
print('Chọn cột so1\n', dataframe_1['so1'])
# Chọn nhiều dòng
print('Chọn nhiều dòng\n', dataframe_1[0:3])
# Chọn nhiều cột
print('Chọn nhiều cột\n', dataframe_1[['so1', 'so3']])
# Chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', dataframe_1.iloc[:3, :2])
# Xóa cột
dataframe_1 = dataframe_1.drop(columns=['so1', 'so4'])
print(dataframe_1)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]
Dataframe dictionary: 
     Name  Age
0   Jonh   30
1  Smith   40
Dataframe dictionary: 
         so1       so2       so3       so4
0 -0.773596 -0.816741  0.956413 -1.049704
1  1.245442  0.061874  1.686700  1.098827
2  0.078198 -0.078071  1.186577  0.255383
3 -2.231912  0.958241 -0.523999 -0.183292
4  0.462676 -0.803385  1.566892 -0.430408
Chọn cột so1
 0    -0.773596
1     1.245442
2     0.078198
3    -2.231912
4     0.462676
5     0.117478
6     0.234237
7     0.848880
8     1.131077
9     0.277879
10    0.304692
11   -0.536504
12    0.534266
13   -1.115148
14   -0.863967
15   -1.176805
16    0.926315
17    0.288454
18   -0.061633
19   -1.026189
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.773596 -0.816741  0.956413 -1.049704
1  1.245442  0.061874  1.686700  1.098827
2  0.078198 -0.078071  1.186577  0.255383
Chọn nhiều cột
          so1       so3
0  -0.773596  0.956413
1   1.

7.1. Nối nhiều DataFrame

In [ ]:
# @title
#Nối 2 Dataframe
df1 = pd.DataFrame({'Name': ['John', 'Smith', 'Paul'],
                    'Age': [25, 30, 50]}
                   ,index = [0, 1, 2])
df2 = pd.DataFrame({'Name': ['Adam', 'Smith'],
                    'Age': [26, 11]}
                   ,index = [3, 4])
df_concat = pd.concat([df1, df2])
print('Noi 2 dataframe\n', df_concat)
print('Xoa cot trung lap\n', df_concat.drop_duplicates('Name'))
print('Sap xep theo Dataframe\n', df_concat.sort_values('Age'))
df_rename = df_concat.rename(columns={'Name': "Surname", 'Age':'Age_pupil'})
print('Sap xep theo Dataframe\n', df_rename)

Noi 2 dataframe
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Xoa cot trung lap
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sap xep theo Dataframe
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Sap xep theo Dataframe
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


7.2 Đọc dữ liệu từ CSV

In [ ]:
# @title
path = 'Salary_Data.csv'
COLUMNS = ['YearsExpericence', 'Salary']
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

7.3. Gom nhóm dữ liệu DataFrame

In [ ]:
# @title
path = 'Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col = False)
print(df_csv.head())
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

# **Numpy và Pandas bài tập**

1. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tất cả các phần tử trong mảng khác 0 (tìm hiểu hàm all của numpy)

In [ ]:
# @title
import numpy as np

arr_input = np.random.randint(20, size = (3, 3))
result = np.all(arr_input != 0)
print("Ma tran la: \n", arr_input)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0:  Khong


2. Tạo mảng 20 số nguyên ngẫu nhiên kích thước 3 x 3 có giá trị trong khoảng [0, 20]. Viết
chương trình kiểm tra tồn tại một phần tử trong mảng khác 0 (tìm hiểu hàm any của numpy)

In [ ]:
# @title
import numpy as np

bt2 = np.random.randint(20, size = (3, 3))
result = np.any(bt1 != 0)
print("Ma tran la: \n", bt1)
print("Cac gia tri co khac 0:", "Co" if result else "Khong")

Ma tran la: 
 [[13 15  0]
 [13 17  4]
 [ 9 18  4]]
Cac gia tri co khac 0: Co


3. Sinh viên tìm hiểu và viết chương trình sử dụng các hàm sau numpy.greater,
numpy.greater_equal, numpy.less, và numpy.less_equal để so sánh 2 mảng 1 chiều, 2 chiều.

In [ ]:
# @title
vector_1 = np.array([1,3])
vector_2 = np.array([2,2])

matrix_1 = np.array([[1,1], [3,3]])
matrix_2 = np.array([[2,2], [2,2]])

print(np.less(vector_1, vector_2))
print(np.less(matrix_1, matrix_2))

[ True False]
[[ True  True]
 [False False]]


4. Viết chương trình tạo mảng gồm 10 số 1, 10 số 0 và 10 số 5

In [ ]:
# @title
matrix_1x10 = np.full(10, 1)
matrix_0x10 = np.full(10, 0)
matrix_5x10 = np.full(10, 5)
print(matrix_1x10)
print(matrix_0x10)
print(matrix_5x10)

[1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0 0 0 0]
[5 5 5 5 5 5 5 5 5 5]


5. Viết chương trình tạo mảng số nguyên chẳn từ [30, 70]

In [ ]:
# @title
arr_30to70 = np.arange(30, 70)
print(arr_30to70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
(Tìm hiểu hàm identity của numpy)

In [ ]:
# @title
matrix_donvi = np.identity(3)

print(matrix_donvi)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Viết chương trình tạo mảng 10 phần tử trong khoảng [15, 55]. In các giá trị ngoài trừ phần tử
đầu và cuối

In [ ]:
# @title
result = np.random.randint(15, 55, size = (3))[1:-1]
print(result)

[45]


8. Viết chương trình tạo mảng 20 phần tử trong khoảng [0, 20] và đổi dấu những số nằm trong
khoảng [9, 15]

In [ ]:
# @title
import numpy as np

arr_input = np.random.randint(0, 20, size=10)
arr_condition = np.arange(9, 15)

condition = np.isin(arr_input, arr_condition)
result = np.where(condition, arr_input, -arr_input)

print(result)

[ 11  12   0  -1  -4 -19  -3   9 -15  -8]


9. Viết chương trình tạo ma trận 3 x 4 và mỗi phần tử có giá trị [10, 21]

In [ ]:
# @title
import numpy as np

result = np.random.randint(10, 21,size = (3,4))
print(result)

[[11 20 14 10]
 [11 18 13 10]
 [10 20 18 10]]


10. Viết chương trình tạo ma trận 10 x 10, các phần tử ở biên có giá trị 1, các phần tử bên trong có
giá trị 0

In [ ]:
# @title
import numpy as np
matrix_10x10 = np.full((10, 10), 1)
matrix_10x10[1:-1, 1:-1] = 0
print(matrix_10x10)


[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


11. Viết chương trình tạo ma trận 5 x 5, các phần tử ở đường chéo chính là 1, 2, 3, 4, 5. (tìm hiểu
hàm diag của numpy)

In [ ]:
# @title
import numpy as np
arr_5x5 = np.diag([1,2,3,4,5])
print(arr_5x5)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum
của numpy)

In [ ]:
# @title
import numpy as np
arr_input = np.random.randint(10, size=(3,3,3))

sum_col = arr_input.sum(axis=0)
sum_row = arr_input.sum(axis=1)

print("Tổng cột:\n", sum_col)
print("Tổng hàng:\n", sum_row)

Tổng cột:
 [[11 10 11]
 [16 18 12]
 [18 14  6]]
Tổng hàng:
 [[11 16  4]
 [19 11 10]
 [15 15 15]]


13. Tạo 2 vector ngẫu nhiên 10 phần tử. Thực hiện inner product (np.dot)

In [ ]:
# @title
import numpy as np

v1 = np.random.randint(0, 10, size = 2)
v2 = np.random.randint(0, 10, size = 2)
# Tích vô hướng (v11*v21) + (v12*v22) + ...
inner_product = np.dot(v1, v2)
print("vector1:", v1)
print("vector2:", v2)
print("Inner product:", inner_product)

vector1: [7 8]
vector2: [2 7]
Inner product: 70


14. Tạo ma trận A= 4 x 3 và vector y gồm 3 phần tử ngẫu nhiên. Thêm vector y vào từng dòng của
ma trận A

In [ ]:
# @title
import numpy as np

matrix_4x3 = np.full((4, 3), 0)
print(matrix_4x3)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
# @title
import pandas as pd
# Seies: một mảng một chiều có gắn index
pd_serie1 = pd.Series([2, 4, 6, 8, 10])
pd_serie2 = pd.Series([1, 3, 5, 7, 10])

cong = pd_serie1 + pd_serie2
tru = pd_serie1 - pd_serie2
nhan = pd_serie1 * pd_serie2
chia = pd_serie1 % pd_serie2

print("Cong: \n", cong)
print("Tru: \n", tru)
print("Nhan: \n", nhan)
print("Chia: \n", chia)


Cong: 
 0     3
1     7
2    11
3    15
4    20
dtype: int64
Tru: 
 0    1
1    1
2    1
3    1
4    0
dtype: int64
Nhan: 
 0      2
1     12
2     30
3     56
4    100
dtype: int64
Chia: 
 0    0
1    1
2    1
3    1
4    0
dtype: int64


16. Viết chương trình Pandas chuyển đổi cột đầu tiên thành Series (Tìm hiểu thuộc tính ix của
pandas)

In [ ]:
# @title
import numpy as np
import pandas as pd
arr_input = np.random.randint(0, 12, size = (5, 3))
pd_dataframe = pd.DataFrame(arr_input, columns = ['col1', 'col2', 'col3'])
pd_series_1_column = pd_dataframe.iloc[:,0]

print('Panda data frame: \n',pd_dataframe)
print('First column to Series: \n',pd_series_1_column)

Panda data frame: 
    col1  col2  col3
0    10     1     5
1     2    10     8
2     4    11     1
3     4     8    10
4     2     3     9
First column to Series: 
 0    10
1     2
2     4
3     4
4     2
Name: col1, dtype: int64


17. Viết chương trình Pandas sắp xếp theo cột của DataFrame 4 x 3 ngẫu nhiên

In [ ]:
# @title
import numpy as np
import pandas as pd
arr_input = np.random.randint(1, 11, size = (4, 3))
pd_dataframe = pd.DataFrame(arr_input)
pd_dataframe_column_sorted = pd_dataframe.sort_values(by=[0, 1, 2])

print('Dataframe chua sap xep: \n', pd_dataframe)
print('Dataframe sau sap xep: \n', pd_dataframe_column_sorted)


Dataframe chua sap xep: 
    0   1  2
0  1   4  2
1  7  10  5
2  1   5  2
3  7   7  4
Dataframe sau sap xep: 
    0   1  2
0  1   4  2
2  1   5  2
3  7   7  4
1  7  10  5


18. Viết chương trình Pandas thay đổi index của một Series (dùng pandas.reindex)

In [ ]:
# @title
import pandas as pd
input_series = pd.Series([1, 2, 3, 4, 5])
print(input_series)
input_series = input_series.set_axis(['A', 'B', 'C', 'D', 'E'])
print(input_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64
A    1
B    2
C    3
D    4
E    5
dtype: int64


# **Tensor lý thuyết**

3.1. Tensor 0 chiều

In [ ]:
# @title
import tensorflow as tf

rank0_tensor = tf.constant(4)
r1_int = tf.constant(4, tf.int16)
r2_float = tf.constant(4.0, tf.float32)
r3_string = tf.constant("Hello HUIT", tf.string)

print(rank0_tensor)
print(r1_int)
print(r2_float)
print(r3_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int16)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(b'Hello HUIT', shape=(), dtype=string)


3.2. Tensor 1-chiều

In [ ]:
# @title
import tensorflow as tf

rank1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


3.3. Tensor 2-chiều (ma trận)

In [ ]:
# @title
import tensorflow as tf

rank2_tensor = tf.constant([[1,2], [3,4], [5,6]])
print(rank2_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


3.4. Tensor n-chiều (nhiều trục)

In [ ]:
# @title
rank_3_tensor = tf.constant([
    [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]]
])
print(rank_3_tensor)

tf.Tensor(
[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]], shape=(3, 2, 3), dtype=int32)


3.5. Thuộc tính của tensor

In [ ]:
# @title
import tensorflow as tf
rank_3_tensor = tf.constant([
     [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]],
    [[1,2,3],
     [1,2,3]]
])
print(rank_3_tensor)
print('shape: ', rank_3_tensor.shape)
print('type of tensor: ', rank_3_tensor.dtype)

3.6. Tạo tensor tự động gán giá trị 0 ban đầu

In [ ]:
# @title
rank1_zero = tf.zeros(10)
print(rank1_zero)

rank2_zero = tf.zeros([2,3])
print(rank2_zero)

rank3_zero = tf.zeros([2, 3, 3])
print(rank3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


3.7 Tạo tensor tự động gán giá trị 1 ban đầu

In [ ]:
# @title
import tensorflow as tf
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3,3])
print(t_2_one)

t_3_one = tf.ones([3, 4, 5])
print(t_3_one)

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 4, 5), dtype=float32)


3.8. Tạo tensor tự động với giá trị bất kỳ

In [ ]:
# @title
rank1 = tf.fill(3,10)
print(rank1)

rank2 = tf.fill([2,2],1)
print(rank2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


3.9. Tạo tensor 1-chiều với hàm linspace


In [ ]:
# @title
# Hàm linspace tạo một tensor với số phần tử mong muốn trong một phạm vi nhất định
lin_tensor = tf.linspace(5, 2, 3)
print(lin_tensor)

tf.Tensor([5.  3.5 2. ], shape=(3,), dtype=float64)


3.10. Tạo tensor 1-chiều với hàm range

In [ ]:
# @title
range_tensor = tf.range(3, 7, 0.5)
print(range_tensor)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)


3.11. Tạo tensor với giá trị ngẫu nhiên

In [ ]:
# @title
# normal
range_tensor = tf.random.normal([5])
print("\nNormal:")
print(range_tensor)
range_tensor = tf.random.normal([3,3])
print(range_tensor)

# truncated
range_tensor = tf.random.truncated_normal([5])
print("\nTruncated normal:")
print(range_tensor)
range_tensor = tf.random.truncated_normal([3,3])
print(range_tensor)

# uniform
range_tensor = tf.random.uniform([5])
print("\nUniform:")
print(range_tensor)
range_tensor = tf.random.uniform([3,3])
print(range_tensor)


Normal:
tf.Tensor([-0.2846495  -1.3848633  -0.80137026 -0.9842483   2.5473914 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 5.3582501e-02 -8.6850774e-01 -1.6533083e-01]
 [-1.1131105e+00  8.4209430e-04  3.2286305e-02]
 [-8.1277877e-01 -1.0661209e+00  1.2439115e+00]], shape=(3, 3), dtype=float32)

Truncated normal:
tf.Tensor([ 0.06816915  0.2126186   0.01331513 -0.07993142  0.189185  ], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.09438159 -0.32365647  0.22455426]
 [-0.8297255   0.46307132 -1.7049134 ]
 [ 0.09177887 -1.094745    0.41500062]], shape=(3, 3), dtype=float32)

Uniform:
tf.Tensor([0.4493382  0.91022694 0.14004326 0.05444658 0.6803819 ], shape=(5,), dtype=float32)
tf.Tensor(
[[0.01586652 0.49280667 0.4354254 ]
 [0.1795038  0.32228732 0.40993798]
 [0.6389053  0.89317036 0.8799957 ]], shape=(3, 3), dtype=float32)


3.12. Chuyển đổi kiểu dữ liệu

In [ ]:
# @title


In [ ]:
# @title
t_float = tf.constant(3.9, tf.float32)
print(t_float, '---', t_float.dtype)
t_int = tf.cast(t_float, dtype = tf.int32)
print(t_float, '---', t_float.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>


3.13. Cac phep toan trong tensor flow

In [ ]:
# @title
# Can bac 2
x = tf.constant(2, dtype=tf.float32)

# Cong 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.add(a,b)
tong = a + b

# Nhan 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)
c = tf.multiply(a,b)
tich = a * b

print(x)
print(tong)
print(tich)

tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)


In [ ]:
# @title
import tensorflow as tf

a = tf.constant([6. , 6. , 6.])
b = tf.constant([4. , 4. , 4.])
c = tf.constant([3. , 3. , 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

3.14. Các phép toán làm tròn và so sánh

In [ ]:
# @title
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r1)
print(r2)
print(r3)
print(r4)

tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


3.15. Các phép toán trên vector và ma trận

In [ ]:
# @title
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

3.16. Biến trong tensorflow

In [ ]:
# @title
var1 = tf.Variable(8.5, dtype = tf.float32)
var2 = tf.Variable([5,9], dtype = tf.float32)
print(var1)
print(var1.shape)
print(var1.dtype)
print(var2)
print(var2.shape)
print(var2.dtype)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
()
<dtype: 'float32'>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([5., 9.], dtype=float32)>
(2,)
<dtype: 'float32'>


3.18. Modules, Layers và Models

SimpleModule xử lý tensor scalar

In [ ]:
# @title
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        # 5.0 Giá trị ban đầu của biến
        self.trainable_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        return self.trainable_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name = 'simple')

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variable', simple_module.trainable_variables)
print('All variable', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variable (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variable (<tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>)


Model với nhiều tầng

In [ ]:
# Lớp này có các thông tin như sau:
# Khởi tạo:
#   in_features số cột đầu vào
#   out_features số cột đầu ra

class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        # Random theo phân phối Gauss
        self.w = tf.Variable(tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__ (self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)
    def __call__ (self, x):
        x = self.dense_1(x)
        result = self.dense_2(x)
        return result
my_model = SequentialModule(name = "the_model")

print("Model results: ", my_model(tf.constant([[2.0, 2.0, 2.0]])))


Model results:  tf.Tensor([[2.7700772 0.       ]], shape=(1, 2), dtype=float32)


# **Tensor bài tập**

1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [ ]:
import tensorflow as tf

tensor_0 = tf.zeros([2, 3])
print(tensor_0)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


2. Cho X = [[1, 2, 3], [4, 5, 6]], hãy tạo tensor có kích thước và dtype như X với các phần tử được
gán 0

In [ ]:
x_0 = tf.zeros([2, 3], dtype='int32')
print(x_0)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


3. Tạo một tensor có kích thước [3, 2] với các phần tử được gán 5

In [ ]:
tensor_5 = tf.fill([3, 2], 5)
print(tensor_5)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


4. Tạo một tensor 1-chiều với 50 phần tử chẵn trong khoảng [5, 10]

In [ ]:
tensor_50 = tf.linspace(5, 10, 50)
print(tensor_50)

tf.Tensor(
[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ], shape=(50,), dtype=float64)


5. Tạo một tensor 1-chiều có giá trị như [10, 12, 14, …, 100]

In [ ]:
tensor_range_10_100 = tf.range(10, 100, delta=2)
print(tensor_range_10_100)

tf.Tensor(
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98], shape=(45,), dtype=int32)
